### ISSUE TITLE
solaris is necessary？

### ISSUE THREAD

**Issue by asd790320224** [biasvariancelabs/aitlas-arena#1]
When I run ‘train_and_evaluate.json’, it prompts me to install ‘solaris’, but none of the dependencies required by solaris can be installed on the Python3.8 platform. The project environment is in Python3.8, causing me to be unable to install 'solaris' and can't execute the corresponding json.
I would like to ask how to solve this problem? Does 'solaris' have to be imported?

**Comment by simidjievskin** [comment]
Hi,

can you please provide more specific details of the issue/error? 'solaris' requires 'gdal' which needs to be installed independatly on a Windows machine (as we outline in the instalation guide https://github.com/biasvariancelabs/aitlas). As of now, it's used for the evaluator within unet (w/ an efficientnet backbone).  Nevertheless, indeed, 'solaris' can be a bit problematic, and we are going through refactoring of the code. 

cheers

**Comment by asd790320224** [comment]
Yes, I have followed the guide to install those three plugins.(GDAL-3.4.3, Fiona-1.8.21 and rasterio-1.2.10, all of them are -cp38-cp38-win_amd64.whl which suitable for my plateform)

I can only run 'split.json'. When I run 'train_and_evaluate.json', It reports an error
![1701429287282](https://github.com/biasvariancelabs/aitlas-arena/assets/121183108/bce41e77-18ce-4462-91f4-7de0b19f236f)
So I tried to install ‘solaris’ manually (in the requirements.txt, the installation of 'solaris' was marked with ‘#’)
But...
![1701432001937](https://github.com/biasvariancelabs/aitlas-arena/assets/121183108/6f82619d-73f6-437d-a159-d3ea151b6632)
None of these dependencies can be installed in py3.8, but the project is running in Python3.8...

Thank you

**Comment by simidjievskin** [comment]
Hi,

thanks for the output. As I said in the previous comment 'solaris' is not required if you are not using UnetEfficentNet. 

From the screenshot, I assume you are not - so a quick workaround is commenting the line 
`#from .unet_efficientnet import UNetEfficientNet` in `aitlas\models\__init__.py`. 

cheers,

**Comment by asd790320224** [comment]
Thank you!!!
I would like to ask if this training is performed using the GPU by default? (If GPU conditions permit)
Now I use CPU for training, and the speed is very slow... Unfortunately, my computer configuration is not enough... If it can use GPU for training, then I want to try using a computer with CUDA installed.

**Comment by simidjievskin** [comment]
Yes - if a cuda device is available, it will run on it.

cheers,
